---
# tasks file for docker-install

- name: Install docker dependencies
  become: yes
  apt:
    name: "{{ docker_dep_packages }}"
    state: present

- name: Check if docker-ce already exists
  become: yes
  command:
    argv:
      - docker
      - version
  register: docker_exists

- name: Show that docker already exists
  debug:
    var: docker_exists.stdout_lines
  when: docker_exists is success

- name: Add Docker GPG key
  become: yes
  apt_key:
    url: "{{ docker_apt_key }}"
    state: present
  when: docker_exists is failed
  

- name: Create docker-install working folder
  file:
    path: /home/{{ ansible_user_id }}/.acd_docker_install
    state: directory

- name: Download Docker installer script
  uri:
    url: https://get.docker.com
    dest: /home/{{ ansible_user_id }}/.acd_docker_install/get-docker.sh
  when: docker_exists is failed

- name: Download Docker installer script
  become: yes
  command:
    argvs:
      - sh
      - /home/{{ ansible_user_id }}/.acd_docker_install/get-docker.sh
  when: docker_exists is failed

- name: Install docker-compose
  become: yes
  pip:
    name: docker-compose

- name: Verify Docker installation
  become: yes
  command:
    argvs:
      - docker
      - run
      - hello-world
  register: docker_verify
  when: docker_exists is failed

  
- name: Print Docker installation verify
  debug:
    var: docker_verify.stdout_lines
  when: docker_exists is failed