---
# vars file for rpi-mqtt-monitor

repo_url: "https://github.com/ironsheep/RPi-Reporter-MQTT2HA-Daemon.git"
required_packages:
  - git
  - python3
  - python3-pip 
  - python3-tzlocal
  - python3-sdnotify
  - python3-colorama
  - python3-unidecode
  - python3-paho-mqtt
