---
# tasks file for common

- name: Install nessecary packages
  become: yes
  apt:
    name: "{{ common_packages }}"
    state: present

- name: Set timezone to {{ common_timezone }}
  become: yes
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Generate locale {{ common_locale }}
  become: yes
  locale_gen:
   name: "{{ common_locale }}"
   state: present

- name: Set locale-time to {{ common_locale }}
  become: yes
  command:
    argv:
      - localectl
      - set-locale
      - LC_TIME={{ common_locale }}

- name: Set locale to {{ common_locale }}
  become: yes
  command:
    argv:
      - localectl
      - set-locale
      - LANG={{ common_locale }}

- name: Copy template .profile
  template:
    src: .profile.j2
    dest: /tmp/.profile
    mode: 0744

- name: Fetch generated .profile
  slurp:
    src: /tmp/.profile
  register: profile

- name: Append to .profile
  blockinfile:
    backup: yes
    block: "{{ profile['content'] | b64decode }}"
    destfile: /home/{{ ansible_user_id }}/.profile
    insertafter: EOF

- name: Create working dir for {{ common_hostname }}
  file:
    path: /home/{{ ansible_user_id }}/.acd_{{ common_hostname }}
    state: directory
    mode: 0764
  


- name: Set manually hostname to {{ common_hostname }}
  become: yes
  command:
    argv:
      - hostnamectl
      - set-hostname
      - "{{ common_hostname }}"

- name: Set host icon to {{ common_host_icon }}
  become: yes
  command:
    argv:
      - hostnamectl
      - set-icon-name
      - "{{ common_host_icon }}"

- name: Set host chassis to {{ common_host_chassis }}
  become: yes
  command:
    argv:
      - hostnamectl
      - set-chassis
      - "{{ common_host_chassis }}"

- name: Set host deployment to {{ common_host_deployment }}
  become: yes
  command:
    argv:
      - hostnamectl
      - set-deployment
      - "{{ common_host_deployment }}"

- name: Set host location to {{ common_host_location }}
  become: yes
  command:
    argv:
      - hostnamectl
      - set-location
      - "{{ common_host_location }}"

- name: Fetch hostnamectl info
  become: yes
  command:
    argv:
      - hostnamectl
  register: hostout
  changed_when: hostout.rc != 0

- name: Print hostnamectl info
  debug:
    var: hostout.stdout_lines
  