name: Release

on:
  push:
   tags:
      - "*"

jobs:
  build:
    runs-on: [self-hosted, linux]
    container: ckozis/ansible-dev-container:latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build collection
        run: ansible-galaxy collection build