---
# tasks file for pihole

- name: Check if Docker exists
  become: yes
  command:
    argv:
      - docker
      - version

- name: Create Docker working dir for acd_pihole
  file:
    path: /home/{{ ansible_user_id }}/.acd_pihole/
    state: directory

- name: Copy pihole-stack compose file
  template:
    src: /temlates/docker-compose.yml.j2
    dest: "/home/{{ ansible_user_id }}/.acd_pihole/docker-compose.yml"

- name: Deploy pihole-stack
  become: yes
  command:
    chdir: /home/{{ ansible_user_id }}/.acd_pihole/
    argv:
      - docker-compose
      - up
      - -d
